### ISSUE TITLE
Winter 2024 Release 🎅🎄

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/profile#13]
## Tasks

- [x] Write first unit tests with Pester [1]
- [x] Add GitHub Actions worklow
- [x] ~~Implement `Stop-ElevatedConsole`~~ (Note: deprecated)
- [x] Update PowerShell Version and review list of new language features
- [x] ~~Move `Get-WorldClock` to configuration repository~~ (Note: deprecated)

## References

- https://devblogs.microsoft.com/scripting/unit-testing-powershell-code-with-pester/

**Comment by StefanGreve** [comment]
Blocked by #14
