### ISSUE TITLE
Documentation 🎅🎄

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/profile#16]
## TODO

- [x] Add proper documentation to all Cmdlets

## Stretch Goals

- [x] Think about localization
- [x] Export aliases as well (if this turns out to be too much work, move this task in a separate ticket)

**Comment by StefanGreve** [comment]
After giving it some thought, I have concluded that keeping the local to `en-US` is the most sensible choice for the current use-case.
