### ISSUE TITLE
MacOS Bugs

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/profile#18]
## TODOS

Implement a solution for all these issues on MacOS (ignoring Linux compatibility for now):

- [x] #7 
- [x] #21
- [ ] #22
- [ ] #23 
- [ ] Stop-LocalServer (Get-NetTCPConnection DNE on MacOS/Linux)
- [ ] Install-Certificate (requires further testing)
- [ ] Test `git-fire` on MacOS and resolve TODO comments in code
- [ ] Remove the `Force` flag from `Set-EnvironmentVariable` (skip this step with a warning instead)

Treatment of environment variables on non-Windows platforms for non-process scopes may require special attention (see also: [1])

- [ ] Set-EnvironmentVariable
- [ ] Get-EnvironmentVariable
- [ ] Remove-EnvironmentVariable

## References

- [1] https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4
