### ISSUE TITLE
Linux Roadmap

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/profile#6]
After testing this profile on Linux I noticed a few issues that should be addressed in the next release:

- [x] use `:` as split character in `Get-EnvironmentVariable`, `Set-EnvironmentVariable` and `Remove-EnvironmentVariable` on Linux
- [x] The prompt function is broken in many ways:
  - [x] `$env:USERNAME` isn't set by default in Raspbian OS
  - [x] same goes for `$env:COMPUTERNAME`
  - [x] ~the active branch isn't detected correctly~ _edit: it works with a fairly new version of Git_
- [x] alias `winfetch` to `neofetch` on Windows
- [x] the performance (time to load profile) is really bad (`Loading personal and system profiles took 4140ms.`)
  - [x]  configure automatic transcript recording preferences via an environmental variable and opt out by default

Additionally, update the `README.md` file to include further tips and tricks for Unix-based operating systems.
